apiVersion: v1
kind: Namespace
metadata:
  name: turbologger
  labels:
    name: turbologger
    app.kubernetes.io/name: turbologger
    app.kubernetes.io/component: logging
    app.kubernetes.io/version: "1.0.0"